### ISSUE TITLE
Hydra-router / Docker Swarm / AWS: Getting SIGTERM

### ISSUE THREAD

**Issue by mozrat** [flywheelsports/hydra-router#151]
Hello @cjus 

I've tried to deploy my app into AWS this evening and I can't work out why hydra-router is constantly failing with a SIGTERM signal

```
Starting service hydra-router:1.4.31 on 10.0.2.8:5353
[2017-11-18T00:45:27.566Z] INFO (1 on 90b5a3641439): Starting service hydra-router:1.4.31 on 10.0.2.8:5353
ts: "2017-11-18T00:45:27.565Z"
serviceName: "hydra-router"
type: "info"
processID: 1
Detected IPv4 IPs:
* lo: 127.0.0.1 255.0.0.0
* lo: 10.0.2.8 255.255.255.255
* eth0: 10.0.2.5 255.255.255.0
* eth1: 172.18.0.3 255.255.0.0
[2017-11-18T00:45:27.580Z] INFO (1 on 90b5a3641439): Starting service hydra-router:1.4.31 on 10.0.2.8:5353
serviceName: "hydra-router"
[2017-11-18T00:45:27.611Z] INFO (1 on 90b5a3641439): HR: hydra-router adding [get]/v1/router/list/:thing
serviceName: "hydra-router"
[2017-11-18T00:45:27.616Z] INFO (1 on 90b5a3641439): HR: hydra-router adding [get]/
serviceName: "hydra-router"

[....]

[2017-11-18T00:46:59.517Z] FATAL (1 on 90b5a3641439): Received SIGTERM
serviceName: "hydra-router"
[2017-11-18T00:46:59.519Z] ERROR (1 on 90b5a3641439): Service is shutting down.
ts: "2017-11-18T00:46:59.519Z"
serviceName: "hydra-router"
type: "error"
processID: 1
[2017-11-18T00:46:59.521Z] ERROR (1 on 90b5a3641439): Service is shutting down.
serviceName: "hydra-router"
ts: "2017-11-18T00:46:59.519Z"
type: "error"
```

Before that, in the logs, my services were populating their routes happily.

Thanks for any pointers you can give.

**Comment by cjus** [comment]
Are you able to post your config file?

**Comment by mozrat** [comment]
@cjus Yes - happy to post those. This works fine in Docker on my development machine started with docker-compose. I'm now trying to get it into AWS with Docker Swarm (and a compose file)

config.js
```
{
  "cluster": false,
  "processes": 0,
  "externalRoutes": {},
  "routerToken": "",
  "disableRouterEndpoint": false,
  "risingStack": false,
  "debugLogging": true,
  "hydra": {
    "serviceName": "hydra-router",
    "serviceDescription": "Service Router",
    "serviceIP": "",
    "servicePort": 5353,
    "serviceType": "router",
    "plugins": {
      "logger": {
        "logRequests": true,
        "redact": ["password"],
        "elasticsearch": {
          "host": "localhost",
          "port": 9200,
          "index": "hydra"
        }
      }
    },
    "redis": {
      "url": "redis://service-redis:6379/15"
    }
  }
}
```

Dockerfile

```
FROM flywheelsports/hydra-router:1.4.31
ADD config.json /usr/src/app/config/config.json
```

docker-compose (slightly redacted)

```
version: '3.1'

services:

  api_proxy:
    image: registry.gitlab.com/xxx/xxx_api_proxy:latest
    logging:
      driver: json-file
    environment:
      NODE_ENV: 'production'
      APP_NAME: '${APP_NAME}'
    networks:
      default: {}
      network:
        aliases:
          - api-proxy
    secrets:
      - demonightly.service.pub
      - demonightly.service.pem
      - demonightly.api_proxy.dbConnection.txt
    depends_on:
      - cache

  api_router:
    image: registry.gitlab.com/xxx/xxx/api_router:latest
    networks:
      network:
        aliases:
          - api-router
    depends_on:
      - cache

  auth:
    image: registry.gitlab.com/xxx/xxx_auth:latest
    environment:
      NODE_ENV: 'production'
      APP_NAME: '${APP_NAME}'
    networks:
      network:
        aliases:
          - service-auth
    secrets:
      - demonightly.service.pub
      - demonightly.service.pem
      - demonightly.auth.dbConnection.txt
    depends_on:
      - cache

  cache:
    image: registry.gitlab.com/xxx/xxx/cache:latest
    networks:
      network:
        aliases:
          - service-redis
    logging:
      driver: awslogs

  datastore:
    image: registry.gitlab.com/xxx/xxx_datastore:latest
    environment:
      NODE_ENV: 'production'
      APP_NAME: '${APP_NAME}'
    networks:
      network:
        aliases:
          - service-datastore
    secrets:
      - demonightly.service.pub
      - demonightly.service.pem
      - demonightly.datastore.dbConnection.txt
    depends_on:
      - cache

  reverse_proxy:
    image: registry.gitlab.com/xxx/xxx/reverse_proxy:latest
    networks:
      network:
        aliases:
          - reverse-proxy
    ports:
      - '${PORT}:80'
    depends_on:
      - ui
      - api_router

  ui:
    image: registry.gitlab.com/xxx/xxx_ui:latest
    environment:
      NODE_ENV: 'production'
      APP_NAME: '${APP_NAME}'
    networks:
      network:
        aliases:
          - service-ui
    secrets:
      - demonightly.service.pub
      - demonightly.service.pem
      - demonightly.ui.dbConnection.txt
    depends_on:
      - cache

networks:
  network:
    driver: overlay

secrets:
  demonightly.service.pub:
    external: true
  demonightly.service.pem:
    external: true
  demonightly.api_proxy.dbConnection.txt:
    external: true
  demonightly.auth.dbConnection.txt:
    external: true
  demonightly.datastore.dbConnection.txt:
    external: true
  demonightly.ui.dbConnection.txt:
    external: true
```
